objects_withfeature_topics:
    # msg_type: DetectedObjectsWithFeature
    - '/perception/object_recognition/detection/clustering/objects_with_feature'
    - '/perception/object_recognition/detection/clustering/camera_lidar_fusion/objects_with_feature'
    - '/perception/object_recognition/detection/clustering/clusters'
    - '/perception/object_recognition/detection/rois0'
    - '/perception/object_recognition/detection/clustering/camera_lidar_fusion/clusters'
detected_object_topics:
    # msg_type: DetectedObject
    - '/perception/object_recognition/detection/centerpoint/objects'
    - '/perception/object_recognition/detection/detection_by_tracker/objects'
    - '/perception/object_recognition/detection/objects'
    - '/perception/object_recognition/detection/camera_lidar_fusion/objects'
    - '/perception/object_recognition/detection/centerpoint/validation/objects'
    - '/perception/object_recognition/detection/clustering/camera_lidar_fusion/objects'
tracked_object_topics:
    - '/perception/object_recognition/tracking/objects'
idl_paths:
    - '/home/anonymous/ACsim/autoware_auto_msgs/autoware_auto_perception_msgs/msg/'
    - '/home/anonymous/ACsim/autoware_auto_msgs/carla_msg/msg/'
    - '/home/anonymous/ACsim/autoware_auto_msgs/tier4_perception_msgs/msg/'