record_topics:
    - '/perception/object_recognition/detection/camera_lidar_fusion/objects'
    - '/perception/object_recognition/detection/centerpoint/objects'
    - '/perception/object_recognition/detection/centerpoint/validation/objects'
    - '/perception/object_recognition/detection/clustering/camera_lidar_fusion/clusters'
    - '/perception/object_recognition/detection/clustering/camera_lidar_fusion/objects'
    - '/perception/object_recognition/detection/clustering/camera_lidar_fusion/objects_with_feature'
    - '/perception/object_recognition/detection/clustering/clusters'
    - '/perception/object_recognition/detection/clustering/objects_with_feature'
    - '/perception/object_recognition/detection/detection_by_tracker/objects'
    - '/perception/object_recognition/detection/objects'
    - '/perception/object_recognition/detection/out/image/compressed'
    - '/perception/object_recognition/detection/rois0'
    - '/perception/object_recognition/objects'
    - '/perception/object_recognition/prediction/maneuver'
    - '/perception/object_recognition/tracking/objects'
    - '/perception/obstacle_segmentation/pointcloud'
    - '/carla_actors'

lidar_topics: 
    - '/perception/object_recognition/detection/centerpoint/objects'
    - '/perception/object_recognition/detection/centerpoint/validation/objects'
    - '/perception/object_recognition/detection/clustering/clusters'
    - '/perception/object_recognition/detection/clustering/objects'
    - '/perception/object_recognition/detection/objects'
    - '/perception/object_recognition/objects'
    - '/perception/object_recognition/tracking/objects'
    - '/perception/obstacle_segmentation/pointcloud'
    - '/carla_actors'

cluster_topics:
    - '/perception/object_recognition/detection/clustering/clusters'
    - '/perception/object_recognition/detection/objects'
    - '/perception/object_recognition/objects'
    - '/perception/object_recognition/tracking/objects'
    - '/perception/obstacle_segmentation/pointcloud'
    - '/carla_actors'